version: "3"

services:
    db:
        image: postgres:12.0-alpine
        container_name: spending-tracker_db
        restart: always
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    web:
        build: .
        container_name: spending-tracker_web
        command: flask run --host $HOST --port $PORT
        restart: on-failure
        volumes:
            - ./:/www/spending_tracker
        ports:
            - $PORT:$PORT
        depends_on:
            - db
        env_file:
            - ./.env

volumes:
    postgres_data:
