version: '3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: prod-spending-tracker_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prod-spending-tracker_web
    restart: always
    command: gunicorn wsgi:create_app() --bind 0.0.0.0:5000
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  postgres_data:
