"""empty message

Revision ID: c07e7f920344
Revises: 
Create Date: 2020-01-12 15:17:21.649385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07e7f920344'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scheduled_transactions', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_transactions', type_='foreignkey')
    op.drop_column('scheduled_transactions', 'user_id')
    # ### end Alembic commands ###
